---

services:

  redis:
    image: redislabs/client-libs-test:8.0-M01
    container_name: redis-standalone
    environment:
      - TLS_ENABLED=yes
      - REDIS_CLUSTER=no
      - PORT=6379
      - TLS_PORT=6666
    command: --enable-debug-command yes --tls-auth-clients optional
    ports:
      - 6379:6379
      - 6666:6666 # TLS port
    volumes:
      - "./dockers/standalone:/redis/work"
    profiles:
      - standalone
      - sentinel
      - replica
      - all

  replica:
    image: ${REDIS_IMAGE:-redis:latest}
    container_name: redis-replica
    depends_on:
      - redis
    command: redis-server --replicaof redis 6379 --protected-mode no
    ports:
      - 6380:6379
    profiles:
      - replica
      - all

  cluster:
    image: redislabs/client-libs-test:8.0-M01
    container_name: redis-cluster
    environment:
      - REDIS_CLUSTER=yes
      - NODES=6
      - TLS_ENABLED=yes
      - PORT=16379
      - TLS_PORT=17379
    command: --tls-auth-clients optional
    ports:
      - "16379-16384:16379-16384"
      - "17379-17384:17379-17384"
    volumes:
      - "./dockers/cluster:/redis/work"
    profiles:
      - cluster
      - all

  sentinel:
    image: ${REDIS_IMAGE:-redis:latest}
    container_name: redis-sentinel
    depends_on:
      - redis
    entrypoint: "redis-sentinel /redis.conf --port 26379"
    ports:
      - 26379:26379
    volumes:
      - "./dockers/sentinel.conf:/redis.conf"
    profiles:
      - sentinel
      - all

  sentinel2:
    image: ${REDIS_IMAGE:-redis:latest}
    container_name: redis-sentinel2
    depends_on:
      - redis
    entrypoint: "redis-sentinel /redis.conf --port 26380"
    ports:
      - 26380:26380
    volumes:
      - "./dockers/sentinel.conf:/redis.conf"
    profiles:
      - sentinel
      - all

  sentinel3:
    image: ${REDIS_IMAGE:-redis:latest}
    container_name: redis-sentinel3
    depends_on:
      - redis
    entrypoint: "redis-sentinel /redis.conf --port 26381"
    ports:
      - 26381:26381
    volumes:
      - "./dockers/sentinel.conf:/redis.conf"
    profiles:
      - sentinel
      - all

  redis-stack:
    image: ${REDIS_STACK_IMAGE:-redis/redis-stack-server:edge}
    container_name: redis-stack
    ports:
      - 6479:6379
    environment:
      - "REDIS_ARGS=--enable-debug-command yes --enable-module-command yes"
    profiles:
      - standalone
      - all

  redis-stack-graph:
    image: redis/redis-stack-server:6.2.6-v15
    container_name: redis-stack-graph
    ports:
      - 6480:6379
    profiles:
      - standalone
      - all
